name       : haskell-auto-update
version    : 0.1.4
release    : 1
source     :
    - http://hackage.haskell.org/package/auto-update-0.1.4/auto-update-0.1.4.tar.gz : 5e96c151024e8bcaf4eaa932e16995872b2017f46124b967e155744d9580b425
license    : MIT
component  : programming.haskell
summary    : This library allows you to define actions which will either be performed by a dedicated thread or, in times of low volume, will be executed by the calling thread.
description: |
    This library allows you to define actions which will either be performed by a dedicated thread or, in times of low volume, will be executed by the calling thread.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
