name       : haskell-auto-update
version    : 0.1.6
release    : 3
source     :
    - https://hackage.haskell.org/package/auto-update-0.1.6/auto-update-0.1.6.tar.gz : f4e023dc8713c387ecf20d851247597fd012cabea3872310b35e911105eb66c4
license    : MIT
component  : programming.haskell
summary    : This library allows you to define actions which will either be performed by a dedicated thread or, in times of low volume, will be executed by the calling thread.
description: |
    This library allows you to define actions which will either be performed by a dedicated thread or, in times of low volume, will be executed by the calling thread.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
